### ISSUE TITLE
Fix padding on bottom of progression chart

### ISSUE THREAD

**Issue by mattnappo** [AleksaGavric/FluentTypeAI#8]
See img: we should add more padding here

![image](https://github.com/AleksaGavric/FluentTypeAI/assets/20868179/ff8cc8c0-6fbb-4e50-a6b7-cf4b924fe46e)

**Comment by mattnappo** [comment]
Is this fixed?

**Comment by AleksaGavric** [comment]
Nope

**Comment by AleksaGavric** [comment]
Fixed.
